plot_context = {'font.size': 10,
                'axes.labelsize': 'medium',
                'axes.titlesize': 'medium',
                'xtick.labelsize': 'x-small',
                'ytick.labelsize': 'x-small',
                'legend.fontsize': 'medium',
                'legend.title_fontsize': None,
                'axes.linewidth': 0.8,
                'grid.linewidth': 0.8,
                'lines.linewidth': 1.5,
                'lines.markersize': 6.0,
                'patch.linewidth': 1.0,
                'xtick.major.width': 0.8,
                'ytick.major.width': 0.8,
                'xtick.minor.width': 0.6,
                'ytick.minor.width': 0.6,
                'xtick.major.size': 1.5,
                'ytick.major.size': 1.5,
                'xtick.minor.size': 2.0,
                'ytick.minor.size': 2.0,
                'figure.autolayout': True,
                'text.usetex': True,
                'font.family': "Helvetica",
                'figure.dpi': 600,
                'figure.figsize': (2.5, 1.7)}
